from admin.Categori.models import Categori
from admin.Customers.models import Customer
from admin.Feedbacks.models import Feedback
from admin.Logs.models import Logs
from admin.OrderItem.models import OrderItem
from admin.Orders.models import Order
from admin.Payments.models import Payment
from admin.Products.models import Product
from admin.Users.models import User
from admin.Address.models import Address