from admin.Customers.route import blueprint as customer_bluprint
from admin.Products.route import blueprint as product_blueprint
from admin.Users.route import blueprint as user_blueprint
from admin.Orders.route import blueprint as order_blueprint
from admin.Categori.route import blueprint as categori_blueprint
from admin.Feedbacks.route import blueprint as feedbacks_blueprint
from admin.Address.route import blueprint as address_blueprint
from admin.Payments.route import blueprint as payments_blueprint
from admin.login.route import blueprint as login_admin
from admin.Logs.route import blueprint as log_blueprint
from admin.Kpi.route import blueprint as kpi_blueprint